"""Alembic migration environment.

Configuration:
- Database URL is read dynamically from ``app.core.config.settings`` (asyncpg).
- ``target_metadata`` is ``app.models.Base.metadata`` (all 14 tables).
- Both offline (SQL emission) and online (async execution) modes are supported.
- ``compare_type`` is enabled so autogenerate detects type drift.
- Comment-only ops and server-default drift are filtered out: historical
  migrations never wrote column comments / server defaults into the DB, so
  comparing them only produces noise and breaks ``alembic check`` as a gate
  (2026-07-28 schema convergence decision).
"""

from __future__ import annotations

import asyncio
from logging.config import fileConfig
from typing import Any

from alembic.operations.ops import (
    AlterColumnOp,
    CreateTableCommentOp,
    DropTableCommentOp,
    MigrationScript,
    ModifyTableOps,
)
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from alembic import context

# Import application settings and model metadata so Alembic can introspect.
from app.core.config import settings
from app.models import Base  # noqa: F401  (ensures all models are registered)

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Model metadata used by autogenerate.
target_metadata = Base.metadata

# Inject the async PostgreSQL URL into the Alembic config so that any
# helper that reads ``config.get_main_option("sqlalchemy.url")`` also works.
config.set_main_option("sqlalchemy.url", settings.postgres_dsn)


def _is_comment_only_op(op: Any) -> bool:
    """True for ops that only touch column/table comments (no structural change)."""
    if isinstance(op, CreateTableCommentOp | DropTableCommentOp):
        return True
    if isinstance(op, AlterColumnOp):
        return (
            op.modify_type is None
            and op.modify_nullable is None
            and op.modify_server_default is False
            and op.modify_name is None
            and op.modify_comment is not False
        )
    return False


def _strip_comment_ops(ops_list: list[Any]) -> list[Any]:
    """Remove comment-only ops, recursing into ModifyTableOps containers."""
    kept: list[Any] = []
    for op in ops_list:
        if _is_comment_only_op(op):
            continue
        if isinstance(op, ModifyTableOps):
            op.ops = _strip_comment_ops(op.ops)
            if not op.ops:
                continue
        kept.append(op)
    return kept


def _render_item(type_: str, obj: Any, autogen_context: Any) -> Any:
    """Skip rendering comment-only ops in autogenerated migration scripts."""
    if _is_comment_only_op(obj):
        return False
    return None


def _process_revision_directives(context: Any, revision: Any, directives: list[Any]) -> None:
    """Drop comment-only ops from generated migration scripts.

    ``alembic check`` builds the diff through this hook, so filtering here
    (not only in ``render_item``) is what keeps ``alembic check`` a clean
    exit-0 gate. Historical migrations never wrote column/table comments
    into the DB, so comment comparison only yields noise (2026-07-28 schema
    convergence decision).
    """
    for script in directives:
        if not isinstance(script, MigrationScript):
            continue
        for upgrade_ops in script.upgrade_ops_list:
            upgrade_ops.ops = _strip_comment_ops(upgrade_ops.ops)
        for downgrade_ops in script.downgrade_ops_list:
            downgrade_ops.ops = _strip_comment_ops(downgrade_ops.ops)


_COMMON_OPTIONS: dict[str, Any] = {
    "target_metadata": target_metadata,
    "compare_type": True,
    "compare_server_default": False,
    "render_item": _render_item,
    "process_revision_directives": _process_revision_directives,
}


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    Emits SQL to stdout without requiring a live DBAPI connection. The URL
    is taken from application settings.
    """

    context.configure(
        url=settings.postgres_dsn,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        **_COMMON_OPTIONS,
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    """Configure context and run migrations within a live connection."""

    context.configure(connection=connection, **_COMMON_OPTIONS)

    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """Run migrations in 'online' mode using an async engine."""

    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


def run_migrations_online() -> None:
    """Entry point for online mode — delegates to the async runner."""

    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
