import type { NavigationItem } from '../types';
import { PlaceholderPage } from './pageShared';
import { DashboardPage, ExclusionsPage, FreezePage, ImportPage, LoopsPage, MappingPage, RadarPage, ReadinessPage, SamplesPage, VerificationPage, VersionsPage } from './sampleLedgerPages';
import { DataSourcePage, DiagnosisPage, EvidencePage, ExportCenterPage, ImplementationPage, LoopEvidencePage, MultiReviewPage, ReevaluationPage, ReviewPage, RollbackPage, SafetyPage, SampleReportPage, TuningPage } from './closureEvidencePages';
import { DeliveryAcceptancePage, HomePage, LineagePage, PerformancePage, QualityRulesPage, RankingPage, RiskOverviewPage, SponsorPage, TodoPage, TrendPage } from './overviewPerformancePages';

export function GenericPage({ route }: { route: NavigationItem }) {
  if (route.id === 'home') return <HomePage route={route} />;
  if (route.id === 'sponsor') return <SponsorPage route={route} />;
  if (route.id === 'risk') return <RiskOverviewPage route={route} />;
  if (route.id === 'todos') return <TodoPage route={route} />;
  if (route.id === 'sample-batches') return <SamplesPage route={route} />;
  if (route.id === 'sample-import') return <ImportPage route={route} />;
  if (route.id === 'readiness') return <ReadinessPage route={route} />;
  if (route.id === 'sample-dashboard') return <DashboardPage route={route} />;
  if (route.id === 'radar') return <RadarPage route={route} />;
  if (route.id === 'freeze') return <FreezePage route={route} />;
  if (route.id === 'mapping') return <MappingPage route={route} />;
  if (route.id === 'verification') return <VerificationPage route={route} />;
  if (route.id === 'exclusions') return <ExclusionsPage route={route} />;
  if (route.id === 'versions') return <VersionsPage route={route} />;
  if (route.id === 'loop-list') return <LoopsPage route={route} />;
  if (route.id === 'kpi') return <PerformancePage route={route} />;
  if (route.id === 'ranking') return <RankingPage route={route} />;
  if (route.id === 'lineage') return <LineagePage route={route} />;
  if (route.id === 'trend') return <TrendPage route={route} />;
  if (route.id === 'diagnosis-list') return <DiagnosisPage route={route} />;
  if (route.id === 'loop-evidence') return <LoopEvidencePage route={route} />;
  if (route.id === 'review') return <ReviewPage route={route} />;
  if (route.id === 'multi-review') return <MultiReviewPage route={route} />;
  if (route.id === 'implementation') return <ImplementationPage route={route} />;
  if (route.id === 'rollback') return <RollbackPage route={route} />;
  if (route.id === 'reevaluation') return <ReevaluationPage route={route} />;
  if (route.id === 'evidence-package') return <EvidencePage route={route} />;
  if (route.id === 'sample-report') return <SampleReportPage route={route} />;
  if (route.id === 'data-source') return <DataSourcePage route={route} />;
  if (route.id === 'rules') return <QualityRulesPage route={route} />;
  if (route.id === 'export-center') return <ExportCenterPage route={route} />;
  if (route.id === 'safety') return <SafetyPage route={route} />;
  if (route.id === 'tuning-sample') return <TuningPage route={route} />;
  if (route.id === 'delivery-scope' || route.id === 'acceptance') return <DeliveryAcceptancePage route={route} />;
  return <PlaceholderPage route={route} />;
}
