import { Link } from 'react-router-dom';
import { LoopTable, MetricCard } from '../components/ui';
import { currentBatch, dataLineage, evidencePackageView, kpis, ledgerExclusions, ledgerMappings, ledgerVerificationItems, ledgerVersions, loopLedgers, loops, mappingGaps, primaryLoopId, sampleScaleNote, tuningCase, valveCheckLoopId } from '../data/mockData';
import type { NavigationItem } from '../types';
import { BatchCard, PageHeader } from './pageShared';

export function SamplesPage({ route }: { route: NavigationItem }) { return <><PageHeader route={route} /><section className="grid two"><BatchCard /><section className="panel"><h2>批次详情</h2><p>{currentBatch.window}</p><p>{sampleScaleNote}</p><ul>{currentBatch.risks.map((risk) => <li key={risk}>{risk}</li>)}</ul><Link className="button" to="/samples/readiness">就绪校验</Link></section></section></>; }
export function ImportPage({ route }: { route: NavigationItem }) { return <><PageHeader route={route} /><section className="grid two"><section className="panel"><h2>导入方式</h2><button>Historian 导出</button><button>CSV 模拟数据</button><button>OPC 只读连接</button><p>当前已接入 demo-data CSV：{dataLineage.csvFile}</p><p>安全边界：当前原型不接真实 DCS、不写 DCS，只读取 historian/CSV/demo 数据。</p><p>字段：{dataLineage.fields.slice(0, 8).join(' / ')} …</p></section><section className="panel"><h2>解析结果</h2><p>字段映射 100%，事件源 {dataLineage.eventsFile} 已接入，采样间隔 {dataLineage.sampleIntervalSeconds}s。</p><p>样本来源：{currentBatch.source}</p><p>支持场景：{dataLineage.scenarios.join(' / ')}。</p><Link className="button" to="/samples/readiness">进入就绪校验</Link></section></section></>; }
export function ReadinessPage({ route }: { route: NavigationItem }) { return <><PageHeader route={route} /><section className="grid four"><MetricCard label="批次映射率" value={`${Math.round(currentBatch.mappedRate * 100)}%`} delta="字段已映射"/><MetricCard label="批次好值率" value={`${Math.round(currentBatch.goodValueRate * 100)}%`} delta="来自 demo-data"/><MetricCard label="评审就绪率" value="94%" delta="缺 MODE 3 条"/><MetricCard label="质量可用率" value="91%" delta="用于评价与诊断"/></section><section className="grid two"><section className="panel"><h2>质量规则</h2><ul><li>GOOD 进入评价</li><li>BAD/FROZEN 降级为数据不足</li><li>MAN 不进入有效自控强结论</li></ul><p>事件可用性：{dataLineage.eventsFile} 已接入，可用于扰动与边界追溯。</p><p>partial 原因：缺 MODE / 质量码片段 / 阀位反馈待补。</p><Link className="button ghost" to="/system/rules">查看质量规则</Link></section><section className="panel"><h2>下一步</h2><p>部分回路不可评估，但 {primaryLoopId}、{valveCheckLoopId}、{tuningCase.loopId} 可进入 P0 主链。</p><p>下一步：先补字段缺口，再冻结样本并进入数据雷达。</p><Link className="button" to="/samples/radar">进入数据雷达</Link></section></section></>; }
export function DashboardPage({ route }: { route: NavigationItem }) { return <><PageHeader route={route} state="success"/><section className="grid four">{kpis.map((kpi) => <MetricCard key={kpi.key} label={kpi.label} value={kpi.value} delta={kpi.delta}/>)}</section><section className="grid two"><section className="panel"><h2>样本规模</h2><p>{dataLineage.loopCount} 回路 / {dataLineage.rowCount} 行 / {dataLineage.sampleIntervalSeconds}s 采样。</p><p>{sampleScaleNote}</p></section><section className="panel"><h2>场景分布</h2><p>normal {dataLineage.scenarioSummary.normal}，oscillation {dataLineage.scenarioSummary.oscillation}，valve_stiction {dataLineage.scenarioSummary.valve_stiction}。</p></section></section></>; }
export function RadarPage({ route }: { route: NavigationItem }) { return <><PageHeader route={route} /><section className="grid two"><section className="panel"><h2>状态分组</h2>{['可评估','可诊断','可整定','需现场核实','数据不足','不可判定'].map((state) => <p className="radar-row" key={state}><span>{state}</span><strong>{loops.filter((loop) => loop.status === state).length}</strong></p>)}</section><section className="panel"><h2>解释区</h2><p>当前样本来自 {dataLineage.datasetId}，按 scenario + quality + mode 派生状态分组。</p><p>{sampleScaleNote}</p><p>重点场景：oscillation {dataLineage.scenarioSummary.oscillation}、valve_stiction {dataLineage.scenarioSummary.valve_stiction}、data_quality_issue {dataLineage.scenarioSummary.data_quality_issue}。</p><LoopTable loops={loops}/></section></section></>; }
export function MappingPage({ route }: { route: NavigationItem }) { return <><PageHeader route={route} state="success"/><section className="panel"><h2>字段映射矩阵</h2><div className="table-wrap"><table><thead><tr><th>源字段</th><th>目标对象</th><th>覆盖率</th><th>状态</th><th>说明</th></tr></thead><tbody>{ledgerMappings.map((item) => <tr key={item.source}><th scope="row">{item.source}</th><td>{item.target}</td><td>{item.coverage}</td><td>{item.status}</td><td>{item.note}</td></tr>)}</tbody></table></div></section><section className="panel"><h2>LoopLedger 契约样例</h2><div className="table-wrap"><table><thead><tr><th>回路</th><th>PV/SP/OP/MODE</th><th>数据可用</th><th>版本引用</th><th>阻断项</th></tr></thead><tbody>{loopLedgers.slice(0, 6).map((item) => <tr key={item.loopId}><th scope="row">{item.loopId}</th><td>{item.pvMapping}/{item.spMapping}/{item.opMapping}/{item.modeMapping}</td><td>{item.dataAvailability}</td><td>{item.versionRefs.join(' / ')}</td><td>{item.blockingItems.join(' / ') || '无'}</td></tr>)}</tbody></table></div></section><section className="grid two"><section className="panel warning-panel"><h2>缺失项</h2><ul>{mappingGaps.map((gap) => <li key={`${gap.field}-${gap.scope}`}><strong>{gap.field}</strong> · {gap.scope} · {gap.action}</li>)}</ul></section><section className="panel warning-panel"><h2>映射边界</h2><p>当前 24 回路为开发 smoke 数据，字段映射可证明链路可运行；P0 评审样本规模需在证据包中保留口径说明。</p><Link className="button ghost" to="/loops/verification">进入台账校核</Link></section></section></>; }
export function VerificationPage({ route }: { route: NavigationItem }) { return <><PageHeader route={route} /><section className="grid two">{ledgerVerificationItems.map((item) => <article className={item.result === '通过' ? 'panel' : 'panel warning-panel'} key={item.name}><h2>{item.name}</h2><strong>{item.result}</strong><p>{item.detail}</p></article>)}</section><section className="panel"><h2>可评审结论</h2><p>验证项将不可证明事项显式留痕：质量码异常不强诊断，阀门粘滞不直接归因为 PID 参数，补证据前 EvidencePackage 维持 partial。</p></section></>; }
export function ExclusionsPage({ route }: { route: NavigationItem }) { return <><PageHeader route={route} /><section className="panel"><h2>排除与降级规则</h2><div className="table-wrap"><table><thead><tr><th>对象</th><th>原因</th><th>有效窗口</th><th>审批状态</th><th>影响</th><th>负责人</th></tr></thead><tbody>{ledgerExclusions.map((item) => <tr key={`${item.loopId}-${item.reason}`}><th scope="row">{item.loopId}</th><td>{item.reason}</td><td>{item.window}</td><td>{item.approval}</td><td>{item.impact}</td><td>{item.owner}</td></tr>)}</tbody></table></div></section><section className="panel warning-panel"><h2>不可自动跨越</h2><p>排除规则不会删除回路，只改变评价口径；被排除对象仍进入 Manifest，以便审计复查。</p></section></>; }
export function VersionsPage({ route }: { route: NavigationItem }) { return <><PageHeader route={route} state="success"/><section className="panel"><h2>台账版本链</h2><div className="table-wrap"><table><thead><tr><th>版本</th><th>类型</th><th>时间</th><th>变更</th></tr></thead><tbody>{ledgerVersions.map((item) => <tr key={item.version}><th scope="row">{item.version}</th><td>{item.type}</td><td>{item.time}</td><td>{item.change}</td></tr>)}</tbody></table></div></section><section className="panel"><h2>当前冻结版本</h2><p>当前使用 ledger.freeze.v0.1 与 {evidencePackageView.manifestVersion}。如样本窗口、字段映射或排除规则变化，证据包必须重算。</p></section></>; }
export function FreezePage({ route }: { route: NavigationItem }) { return <><PageHeader route={route} state="success"/><section className="grid three"><MetricCard label="冻结台账" value="ledger.freeze.v0.1" delta="字段口径已锁定"/><MetricCard label="Manifest Hash" value="demo-7f4c" delta="可用于演示复现"/><MetricCard label="证据包状态" value={evidencePackageView.status} delta="补证据前不升 success"/></section><section className="grid two"><section className="panel"><h2>冻结条件</h2><ul><li>样本窗口固定：{currentBatch.window}</li><li>字段映射版本：mapping.demo-data.v0.1</li><li>质量规则版本：quality-rule.v0.1</li><li>排除规则与 mode mapping 已纳入版本链</li></ul></section><section className="panel warning-panel"><h2>未满足项</h2><ul><li>InstrumentCheckRecord 缺失：{valveCheckLoopId} 需现场阀位反馈</li><li>PostImplementationObservation 缺失：复评观察窗口未闭合</li><li>冻结后不可漂移：新增样本、字段映射或排除规则变化必须生成新版本</li></ul></section></section><section className="panel warning-panel"><h2>冻结说明</h2><p>冻结只保证原型演示复现，不代表真实装置数据已验收；任何新增样本或现场核实记录都会生成新版本。</p></section></>; }
export function LoopsPage({ route }: { route: NavigationItem }) { return <><PageHeader route={route} /><section className="panel"><h2>回路清单</h2><LoopTable loops={loops}/></section></>; }
