import { Link } from 'react-router-dom';
import { LoopTable, MetricCard } from '../components/ui';
import { currentBatch, dataLineage, evidencePackageView, kpis, ledgerExclusions, ledgerMappings, ledgerVerificationItems, ledgerVersions, loopLedgers, loops, mappingGaps, primaryLoopId, sampleScaleNote, tuningCase, valveCheckLoopId } from '../data/mockData';
import type { NavigationItem } from '../types';
import { BatchCard, PageHeader } from './pageShared';
import { SampleImportWizard } from './samples/SampleImportWizard';
import { SampleReadinessWorkbench } from './samples/SampleReadinessWorkbench';

export function SamplesPage({ route }: { route: NavigationItem }) { return <><PageHeader route={route} /><section className="grid two"><BatchCard /><section className="panel"><h2>批次详情</h2><p>{currentBatch.window}</p><p>{sampleScaleNote}</p><ul>{currentBatch.risks.map((risk) => <li key={risk}>{risk}</li>)}</ul><Link className="button" to="/samples/readiness">就绪校验</Link></section></section></>; }
export function ImportPage({ route }: { route: NavigationItem }) { return <><PageHeader route={route} /><SampleImportWizard /></>; }
export function ReadinessPage({ route }: { route: NavigationItem }) { return <><PageHeader route={route} /><SampleReadinessWorkbench /></>; }
export function DashboardPage({ route }: { route: NavigationItem }) { return <><PageHeader route={route} state="success"/><section className="grid four">{kpis.map((kpi) => <MetricCard key={kpi.key} label={kpi.label} value={kpi.value} delta={kpi.delta}/>)}</section><section className="grid two"><section className="panel"><h2>样本规模</h2><p>{dataLineage.loopCount} 回路 / {dataLineage.rowCount} 行 / {dataLineage.sampleIntervalSeconds}s 采样。</p><p>{sampleScaleNote}</p></section><section className="panel"><h2>场景分布</h2><p>normal {dataLineage.scenarioSummary.normal}，oscillation {dataLineage.scenarioSummary.oscillation}，valve_stiction {dataLineage.scenarioSummary.valve_stiction}。</p></section></section></>; }
export function RadarPage({ route }: { route: NavigationItem }) { return <><PageHeader route={route} /><section className="grid two"><section className="panel"><h2>状态分组</h2>{['可评估','可诊断','可整定','需现场核实','数据不足','不可判定'].map((state) => <p className="radar-row" key={state}><span>{state}</span><strong>{loops.filter((loop) => loop.status === state).length}</strong></p>)}</section><section className="panel"><h2>解释区</h2><p>当前样本来自 {dataLineage.datasetId}，按 scenario + quality + mode 派生状态分组。</p><p>{sampleScaleNote}</p><p>重点场景：oscillation {dataLineage.scenarioSummary.oscillation}、valve_stiction {dataLineage.scenarioSummary.valve_stiction}、data_quality_issue {dataLineage.scenarioSummary.data_quality_issue}。</p><LoopTable loops={loops}/></section></section></>; }
export function MappingPage({ route }: { route: NavigationItem }) { return <><PageHeader route={route} state="success"/><section className="panel"><h2>字段映射矩阵</h2><div className="table-wrap"><table><thead><tr><th>源字段</th><th>目标对象</th><th>覆盖率</th><th>状态</th><th>说明</th></tr></thead><tbody>{ledgerMappings.map((item) => <tr key={item.source}><th scope="row">{item.source}</th><td>{item.target}</td><td>{item.coverage}</td><td>{item.status}</td><td>{item.note}</td></tr>)}</tbody></table></div></section><section className="panel"><h2>LoopLedger 契约样例</h2><div className="table-wrap"><table><thead><tr><th>回路</th><th>PV/SP/OP/MODE</th><th>数据可用</th><th>版本引用</th><th>阻断项</th></tr></thead><tbody>{loopLedgers.slice(0, 6).map((item) => <tr key={item.loopId}><th scope="row">{item.loopId}</th><td>{item.pvMapping}/{item.spMapping}/{item.opMapping}/{item.modeMapping}</td><td>{item.dataAvailability}</td><td>{item.versionRefs.join(' / ')}</td><td>{item.blockingItems.join(' / ') || '无'}</td></tr>)}</tbody></table></div></section><section className="grid two"><section className="panel warning-panel"><h2>缺失项</h2><ul>{mappingGaps.map((gap) => <li key={`${gap.field}-${gap.scope}`}><strong>{gap.field}</strong> · {gap.scope} · {gap.action}</li>)}</ul></section><section className="panel warning-panel"><h2>映射边界</h2><p>当前 24 回路为开发 smoke 数据，字段映射可证明链路可运行；P0 评审样本规模需在证据包中保留口径说明。</p><Link className="button ghost" to="/loops/verification">进入台账校核</Link></section></section></>; }
export function VerificationPage({ route }: { route: NavigationItem }) { return <><PageHeader route={route} /><section className="grid two">{ledgerVerificationItems.map((item) => <article className={item.result === '通过' ? 'panel' : 'panel warning-panel'} key={item.name}><h2>{item.name}</h2><strong>{item.result}</strong><p>{item.detail}</p></article>)}</section><section className="panel"><h2>可评审结论</h2><p>验证项将不可证明事项显式留痕：质量码异常不强诊断，阀门粘滞不直接归因为 PID 参数，补证据前 EvidencePackage 维持 partial。</p></section></>; }
export function ExclusionsPage({ route }: { route: NavigationItem }) { return <><PageHeader route={route} /><section className="panel"><h2>排除与降级规则</h2><div className="table-wrap"><table><thead><tr><th>对象</th><th>原因</th><th>有效窗口</th><th>审批状态</th><th>影响</th><th>负责人</th></tr></thead><tbody>{ledgerExclusions.map((item) => <tr key={`${item.loopId}-${item.reason}`}><th scope="row">{item.loopId}</th><td>{item.reason}</td><td>{item.window}</td><td>{item.approval}</td><td>{item.impact}</td><td>{item.owner}</td></tr>)}</tbody></table></div></section><section className="panel warning-panel"><h2>不可自动跨越</h2><p>排除规则不会删除回路，只改变评价口径；被排除对象仍进入 Manifest，以便审计复查。</p></section></>; }
export function VersionsPage({ route }: { route: NavigationItem }) { return <><PageHeader route={route} state="success"/><section className="panel"><h2>台账版本链</h2><div className="table-wrap"><table><thead><tr><th>版本</th><th>类型</th><th>时间</th><th>变更</th></tr></thead><tbody>{ledgerVersions.map((item) => <tr key={item.version}><th scope="row">{item.version}</th><td>{item.type}</td><td>{item.time}</td><td>{item.change}</td></tr>)}</tbody></table></div></section><section className="panel"><h2>当前冻结版本</h2><p>当前使用 ledger.freeze.v0.1 与 {evidencePackageView.manifestVersion}。如样本窗口、字段映射或排除规则变化，证据包必须重算。</p></section></>; }
export function FreezePage({ route }: { route: NavigationItem }) { return <><PageHeader route={route} state="success"/><SampleReadinessWorkbench /></>; }
export function LoopsPage({ route }: { route: NavigationItem }) { return <><PageHeader route={route} /><section className="panel"><h2>回路清单</h2><LoopTable loops={loops}/></section></>; }
