// Auto-generated by prototype/scripts/import-demo-data.mjs. Do not edit by hand.
import type { DiagnosisFinding, EvidencePackage, EvidenceWindow, KpiResult, LoopRecord, SampleBatch, TuningCase } from '../types';

export const demoSampleBatch: SampleBatch = {
  "id": "CLPM-DEMO-SECOND-LEVEL-20260616",
  "name": "demo-data 秒级控制回路样本",
  "source": "CSV:control_loop_second_level_24loops_1h.csv + Metadata:loops_metadata.json + Events:events.csv",
  "window": "2026-06-16T08:00:00+08:00 — 2026-06-16T09:00:00+08:00",
  "loopCount": 24,
  "mappedRate": 1,
  "goodValueRate": 0.99,
  "readiness": "partial",
  "risks": [
    "manual_mode 3 条",
    "data_quality_issue 3 条",
    "valve_stiction 3 条需现场核实"
  ]
};

export const demoDataLineage = {
  "datasetId": "CLPM-DEMO-SECOND-LEVEL-20260616",
  "csvFile": "control_loop_second_level_24loops_1h.csv",
  "metadataFile": "loops_metadata.json",
  "eventsFile": "events.csv",
  "sampleWindow": "2026-06-16T08:00:00+08:00 — 2026-06-16T09:00:00+08:00",
  "sampleIntervalSeconds": 1,
  "rowCount": 86424,
  "loopCount": 24,
  "fields": [
    "timestamp",
    "second",
    "loop_id",
    "loop_tag",
    "unit_name",
    "loop_group",
    "control_type",
    "scenario",
    "pv",
    "sp",
    "op",
    "mode",
    "p",
    "i",
    "d",
    "engineering_unit",
    "quality",
    "event_marker"
  ],
  "scenarios": [
    "normal",
    "oscillation",
    "valve_stiction",
    "manual_mode",
    "data_quality_issue",
    "disturbance",
    "tuning_candidate"
  ],
  "scenarioSummary": {
    "normal": 6,
    "oscillation": 3,
    "valve_stiction": 3,
    "manual_mode": 3,
    "data_quality_issue": 3,
    "disturbance": 3,
    "tuning_candidate": 3
  },
  "safetyBoundary": "Demo data only. No DCS read/write. PID values are simulated parameters."
};

export const demoKpis: KpiResult[] = [
  {
    "key": "auto",
    "label": "样本自控率",
    "value": "94.5%",
    "delta": "24 回路 / 1h 窗口 / 1s 采样",
    "state": "可评估"
  },
  {
    "key": "effective",
    "label": "有效自控率",
    "value": "62.5%",
    "delta": "6 条诊断样例",
    "state": "可诊断"
  },
  {
    "key": "smooth",
    "label": "平稳率",
    "value": "62.5%",
    "delta": "9 条低效",
    "state": "可评估"
  },
  {
    "key": "closure",
    "label": "闭环候选率",
    "value": "50%",
    "delta": "3 条需现场核实",
    "state": "需现场核实"
  }
];

export const demoEvidencePackage: EvidencePackage = {
  "id": "EP-CLPM-DEMO-SECOND-LEVEL-20260616",
  "sampleId": "CLPM-DEMO-SECOND-LEVEL-20260616",
  "manifestVersion": "manifest.demo-data.v0.1",
  "manifestHash": "sha256:demo-7f4c9c1b8e2a",
  "packageStatus": "PACKAGE_PARTIAL",
  "validityStatus": "VALID_WITH_MISSING_REFS",
  "conclusion": "demo-data 秒级样本可支撑从回路绩效、诊断证据到闭环治理的原型演示，但不代表真实算法有效性。",
  "completeness": 0.83,
  "references": [
    "SampleBatch",
    "LoopLedger",
    "KpiResult",
    "DiagnosisFinding",
    "ReviewRecord",
    "EvidenceWindow",
    "InstrumentCheckRecord",
    "PostImplementationObservation",
    "events.csv"
  ],
  "includedRefs": [
    {
      "name": "SampleBatch",
      "status": "已纳入"
    },
    {
      "name": "LoopLedger",
      "status": "已纳入"
    },
    {
      "name": "KpiResult",
      "status": "已纳入"
    },
    {
      "name": "DiagnosisFinding",
      "status": "已纳入"
    },
    {
      "name": "ReviewRecord",
      "status": "已纳入"
    },
    {
      "name": "EvidenceWindow",
      "status": "已纳入"
    },
    {
      "name": "InstrumentCheckRecord",
      "status": "缺失"
    },
    {
      "name": "PostImplementationObservation",
      "status": "缺失"
    },
    {
      "name": "events.csv",
      "status": "已纳入"
    }
  ],
  "missingRefs": [
    "InstrumentCheckRecord",
    "PostImplementationObservation"
  ],
  "riskSummary": [
    "阀门粘滞样例需现场核实",
    "24 回路为开发 smoke 数据，P0 评审需保留样本规模口径",
    "闭环审核存在需补证据项，当前包为 partial"
  ]
};

export const demoLoops: LoopRecord[] = [
  {
    "id": "FIC-1101",
    "device": "气化装置 A",
    "type": "流量",
    "status": "可评估",
    "risk": "low",
    "score": 85,
    "autoRate": 1,
    "smoothRate": 1,
    "nextAction": "保持观察"
  },
  {
    "id": "LIC-1108",
    "device": "气化装置 A",
    "type": "液位",
    "status": "可评估",
    "risk": "low",
    "score": 85,
    "autoRate": 1,
    "smoothRate": 1,
    "nextAction": "保持观察"
  },
  {
    "id": "TIC-1115",
    "device": "气化装置 A",
    "type": "温度",
    "status": "可诊断",
    "risk": "high",
    "score": 58,
    "autoRate": 1,
    "smoothRate": 1,
    "nextAction": "进入证据链并提交审核"
  },
  {
    "id": "PIC-1122",
    "device": "气化装置 A",
    "type": "压力",
    "status": "需现场核实",
    "risk": "medium",
    "score": 85,
    "autoRate": 1,
    "smoothRate": 1,
    "nextAction": "现场核实阀门后复评"
  },
  {
    "id": "AIC-1129",
    "device": "气化装置 A",
    "type": "成分",
    "status": "不可判定",
    "risk": "medium",
    "score": 77,
    "autoRate": 0.59,
    "smoothRate": 1,
    "nextAction": "确认手动原因与投用定义"
  },
  {
    "id": "FIC-1136",
    "device": "气化装置 A",
    "type": "流量",
    "status": "数据不足",
    "risk": "medium",
    "score": 62,
    "autoRate": 0.97,
    "smoothRate": 0.92,
    "nextAction": "补齐质量码和历史窗口"
  },
  {
    "id": "LIC-1143",
    "device": "气化装置 A",
    "type": "液位",
    "status": "可诊断",
    "risk": "medium",
    "score": 58,
    "autoRate": 1,
    "smoothRate": 1,
    "nextAction": "标记扰动并复核评价窗口"
  },
  {
    "id": "TIC-1150",
    "device": "气化装置 A",
    "type": "温度",
    "status": "可整定",
    "risk": "medium",
    "score": 85,
    "autoRate": 1,
    "smoothRate": 1,
    "nextAction": "查看整定样例"
  },
  {
    "id": "PIC-1157",
    "device": "气化装置 A",
    "type": "压力",
    "status": "可评估",
    "risk": "low",
    "score": 85,
    "autoRate": 1,
    "smoothRate": 1,
    "nextAction": "保持观察"
  },
  {
    "id": "AIC-1164",
    "device": "气化装置 A",
    "type": "成分",
    "status": "可评估",
    "risk": "low",
    "score": 85,
    "autoRate": 1,
    "smoothRate": 1,
    "nextAction": "保持观察"
  },
  {
    "id": "FIC-1171",
    "device": "气化装置 A",
    "type": "流量",
    "status": "可诊断",
    "risk": "high",
    "score": 58,
    "autoRate": 1,
    "smoothRate": 1,
    "nextAction": "进入证据链并提交审核"
  },
  {
    "id": "LIC-1178",
    "device": "气化装置 A",
    "type": "液位",
    "status": "需现场核实",
    "risk": "medium",
    "score": 85,
    "autoRate": 1,
    "smoothRate": 1,
    "nextAction": "现场核实阀门后复评"
  },
  {
    "id": "TIC-1185",
    "device": "气化装置 B",
    "type": "温度",
    "status": "不可判定",
    "risk": "medium",
    "score": 77,
    "autoRate": 0.59,
    "smoothRate": 1,
    "nextAction": "确认手动原因与投用定义"
  },
  {
    "id": "PIC-1192",
    "device": "气化装置 B",
    "type": "压力",
    "status": "数据不足",
    "risk": "medium",
    "score": 62,
    "autoRate": 0.97,
    "smoothRate": 0.92,
    "nextAction": "补齐质量码和历史窗口"
  },
  {
    "id": "AIC-1199",
    "device": "气化装置 B",
    "type": "成分",
    "status": "可诊断",
    "risk": "medium",
    "score": 58,
    "autoRate": 1,
    "smoothRate": 1,
    "nextAction": "标记扰动并复核评价窗口"
  },
  {
    "id": "FIC-1206",
    "device": "气化装置 B",
    "type": "流量",
    "status": "可整定",
    "risk": "medium",
    "score": 85,
    "autoRate": 1,
    "smoothRate": 1,
    "nextAction": "查看整定样例"
  },
  {
    "id": "LIC-1213",
    "device": "气化装置 B",
    "type": "液位",
    "status": "可评估",
    "risk": "low",
    "score": 85,
    "autoRate": 1,
    "smoothRate": 1,
    "nextAction": "保持观察"
  },
  {
    "id": "TIC-1220",
    "device": "气化装置 B",
    "type": "温度",
    "status": "可评估",
    "risk": "low",
    "score": 85,
    "autoRate": 1,
    "smoothRate": 1,
    "nextAction": "保持观察"
  },
  {
    "id": "PIC-1227",
    "device": "气化装置 B",
    "type": "压力",
    "status": "可诊断",
    "risk": "high",
    "score": 58,
    "autoRate": 1,
    "smoothRate": 1,
    "nextAction": "进入证据链并提交审核"
  },
  {
    "id": "AIC-1234",
    "device": "气化装置 B",
    "type": "成分",
    "status": "需现场核实",
    "risk": "medium",
    "score": 85,
    "autoRate": 1,
    "smoothRate": 1,
    "nextAction": "现场核实阀门后复评"
  },
  {
    "id": "FIC-1241",
    "device": "气化装置 B",
    "type": "流量",
    "status": "不可判定",
    "risk": "medium",
    "score": 77,
    "autoRate": 0.59,
    "smoothRate": 1,
    "nextAction": "确认手动原因与投用定义"
  },
  {
    "id": "LIC-1248",
    "device": "气化装置 B",
    "type": "液位",
    "status": "数据不足",
    "risk": "medium",
    "score": 62,
    "autoRate": 0.97,
    "smoothRate": 0.92,
    "nextAction": "补齐质量码和历史窗口"
  },
  {
    "id": "TIC-1255",
    "device": "气化装置 B",
    "type": "温度",
    "status": "可诊断",
    "risk": "medium",
    "score": 58,
    "autoRate": 1,
    "smoothRate": 1,
    "nextAction": "标记扰动并复核评价窗口"
  },
  {
    "id": "PIC-1262",
    "device": "气化装置 B",
    "type": "压力",
    "status": "可整定",
    "risk": "medium",
    "score": 85,
    "autoRate": 1,
    "smoothRate": 1,
    "nextAction": "查看整定样例"
  }
];

export const demoEvidenceWindows: EvidenceWindow[] = [
  {
    "loopId": "TIC-1115",
    "title": "TIC-1115 单回路证据链",
    "summary": "来自秒级 demo-data：oscillation 场景，采样间隔 1s，证据窗口 1 小时。",
    "points": [
      {
        "time": "08:00:00",
        "pv": 210.453,
        "sp": 210.161,
        "op": 46.613
      },
      {
        "time": "08:12:00",
        "pv": 207.64,
        "sp": 210.161,
        "op": 47.656
      },
      {
        "time": "08:24:00",
        "pv": 214.041,
        "sp": 210.161,
        "op": 42.299
      },
      {
        "time": "08:36:00",
        "pv": 209.422,
        "sp": 210.161,
        "op": 34.836
      },
      {
        "time": "08:48:00",
        "pv": 210.882,
        "sp": 210.161,
        "op": 9.012
      },
      {
        "time": "09:00:00",
        "pv": 208.582,
        "sp": 210.161,
        "op": 11.866
      }
    ],
    "rules": [
      "PV 围绕 SP 周期振荡",
      "OP 同频动作明显",
      "AUTO 状态下控制未收敛"
    ],
    "events": [
      "08:00:00 window_start · AUTO/GOOD",
      "09:00:00 window_end · AUTO/GOOD"
    ]
  },
  {
    "loopId": "PIC-1122",
    "title": "PIC-1122 单回路证据链",
    "summary": "来自秒级 demo-data：valve_stiction 场景，采样间隔 1s，证据窗口 1 小时。",
    "points": [
      {
        "time": "08:00:00",
        "pv": 3.87,
        "sp": 3.254,
        "op": 48.653
      },
      {
        "time": "08:12:00",
        "pv": 3.24,
        "sp": 3.254,
        "op": 48.052
      },
      {
        "time": "08:24:00",
        "pv": 3.242,
        "sp": 3.254,
        "op": 48.742
      },
      {
        "time": "08:36:00",
        "pv": 3.199,
        "sp": 3.254,
        "op": 48.481
      },
      {
        "time": "08:48:00",
        "pv": 3.277,
        "sp": 3.254,
        "op": 48.218
      },
      {
        "time": "09:00:00",
        "pv": 3.185,
        "sp": 3.254,
        "op": 47.634
      }
    ],
    "rules": [
      "OP 阶梯化变化",
      "PV 响应滞后",
      "需现场核实阀位反馈"
    ],
    "events": [
      "08:00:00 window_start · AUTO/GOOD",
      "09:00:00 window_end · AUTO/GOOD"
    ]
  },
  {
    "loopId": "FIC-1136",
    "title": "FIC-1136 单回路证据链",
    "summary": "来自秒级 demo-data：data_quality_issue 场景，采样间隔 1s，证据窗口 1 小时。",
    "points": [
      {
        "time": "08:00:00",
        "pv": 62.464,
        "sp": 62.891,
        "op": 45.057
      },
      {
        "time": "08:12:00",
        "pv": 66.985,
        "sp": 62.891,
        "op": 39.819
      },
      {
        "time": "08:24:00",
        "pv": 62.879,
        "sp": 62.891,
        "op": 44.009
      },
      {
        "time": "08:36:00",
        "pv": 62.005,
        "sp": 62.891,
        "op": 51.771
      },
      {
        "time": "08:48:00",
        "pv": 62.175,
        "sp": 62.891,
        "op": 54.036
      },
      {
        "time": "09:00:00",
        "pv": 63.638,
        "sp": 62.891,
        "op": 51.913
      }
    ],
    "rules": [
      "PV/SP/OP 字段完整",
      "MODE 与 quality 可用于状态判定",
      "事件线可追溯"
    ],
    "events": [
      "08:00:00 window_start · AUTO/GOOD",
      "08:10:20 quality_bad_start · AUTO/BAD",
      "08:11:41 quality_recovered · AUTO/GOOD",
      "09:00:00 window_end · AUTO/GOOD"
    ]
  }
];

export const demoFindings: DiagnosisFinding[] = [
  {
    "id": "DD-001",
    "loopId": "TIC-1115",
    "findingType": "pid_oscillation",
    "severity": "high",
    "title": "振荡证据充分",
    "confidence": 0.86,
    "evidence": "来自 demo-data 的 oscillation 场景，包含 PV/SP/OP/MODE/quality/event_marker 秒级证据。",
    "evidenceRefs": [
      "EvidenceWindow:TIC-1115",
      "SampleBatch:CLPM-DEMO-SECOND-LEVEL-20260616",
      "quality-rule.v0.1"
    ],
    "action": "进入证据链并提交审核",
    "ownerRole": "控制工程师"
  },
  {
    "id": "DD-002",
    "loopId": "PIC-1122",
    "findingType": "valve_instrument",
    "severity": "medium",
    "title": "疑似阀门粘滞",
    "confidence": 0.74,
    "evidence": "来自 demo-data 的 valve_stiction 场景，包含 PV/SP/OP/MODE/quality/event_marker 秒级证据。",
    "evidenceRefs": [
      "EvidenceWindow:PIC-1122",
      "SampleBatch:CLPM-DEMO-SECOND-LEVEL-20260616",
      "quality-rule.v0.1"
    ],
    "action": "现场核实阀门后复评",
    "ownerRole": "仪表工程师"
  },
  {
    "id": "DD-003",
    "loopId": "AIC-1129",
    "findingType": "manual_mode",
    "severity": "medium",
    "title": "长时间手动模式",
    "confidence": 0.68,
    "evidence": "来自 demo-data 的 manual_mode 场景，包含 PV/SP/OP/MODE/quality/event_marker 秒级证据。",
    "evidenceRefs": [
      "EvidenceWindow:AIC-1129",
      "SampleBatch:CLPM-DEMO-SECOND-LEVEL-20260616",
      "quality-rule.v0.1"
    ],
    "action": "确认手动原因与投用定义",
    "ownerRole": "工艺工程师"
  },
  {
    "id": "DD-004",
    "loopId": "FIC-1136",
    "findingType": "data_condition",
    "severity": "medium",
    "title": "数据质量片段异常",
    "confidence": 0.7,
    "evidence": "来自 demo-data 的 data_quality_issue 场景，包含 PV/SP/OP/MODE/quality/event_marker 秒级证据。",
    "evidenceRefs": [
      "EvidenceWindow:FIC-1136",
      "SampleBatch:CLPM-DEMO-SECOND-LEVEL-20260616",
      "quality-rule.v0.1"
    ],
    "action": "补齐质量码和历史窗口",
    "ownerRole": "数据治理"
  },
  {
    "id": "DD-005",
    "loopId": "LIC-1143",
    "findingType": "disturbance",
    "severity": "medium",
    "title": "工艺扰动影响控制表现",
    "confidence": 0.73,
    "evidence": "来自 demo-data 的 disturbance 场景，包含 PV/SP/OP/MODE/quality/event_marker 秒级证据。",
    "evidenceRefs": [
      "EvidenceWindow:LIC-1143",
      "SampleBatch:CLPM-DEMO-SECOND-LEVEL-20260616",
      "quality-rule.v0.1"
    ],
    "action": "标记扰动并复核评价窗口",
    "ownerRole": "工艺工程师"
  },
  {
    "id": "DD-006",
    "loopId": "TIC-1150",
    "findingType": "tuning_candidate",
    "severity": "low",
    "title": "可整定样例候选",
    "confidence": 0.78,
    "evidence": "来自 demo-data 的 tuning_candidate 场景，包含 PV/SP/OP/MODE/quality/event_marker 秒级证据。",
    "evidenceRefs": [
      "EvidenceWindow:TIC-1150",
      "SampleBatch:CLPM-DEMO-SECOND-LEVEL-20260616",
      "quality-rule.v0.1"
    ],
    "action": "查看整定样例",
    "ownerRole": "授权仪表工程师"
  }
];

export const demoTuningCase: TuningCase = {
  "loopId": "TIC-1150",
  "current": "Kp=1.96, Ti=138s, Td=0s",
  "suggested": "Kp=1.61, Ti=124s, Td=0s",
  "confidence": 0.76,
  "boundary": "来自 demo-data tuning_candidate 场景；仅用于 P0 单条可信整定样例，不代表批量整定，平台不写 DCS。"
};
